name: Code Checks

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: check linting

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - run: pnpm lint

  format:
    runs-on: ubuntu-latest
    name: check formatting
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - run: pnpm format:check

  tsc:
    runs-on: ubuntu-latest
    name: check types
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - run: pnpm type-check
